### ISSUE TITLE
Doesn't connect to wifi

### ISSUE THREAD

**Issue by Gulaschcowboy** [derlucas/homie-sonoff#1]
Hi Lucas,

nice work. After flashing and configuration with the homie app it starts up, but doesn't connect to wifi. Therefore I commented out Homie.disableLogging(); to see what is going on. It starts up until trying to connect to wifi network. After that nothing happens. I did several resets and double checked credentials. AP management doesn't see any connection attempts. Do you have any debug hints?

**Comment by Gulaschcowboy** [comment]
Hi Lucas,

some update: If I choose a open/free Wifi (Freifunk) it connects and starts transmitting to the mqtt.
But temperature and humidity stay at 0 and lumiosity seems to be reversed :

homie/sens1/temperature/value 0
homie/sens1/humidity/value 0
homie/sens1/light/value 605
homie/sens1/temperature/value 0
homie/sens1/humidity/value 0
homie/sens1/light/value 573
homie/sens1/$stats/signal 38
homie/sens1/$stats/uptime 124
homie/sens1/temperature/value 0
homie/sens1/humidity/value 0
homie/sens1/light/value 602 ---> lux(?) exposed to lamp
homie/sens1/light/value 1004 ---> lux(?) with hand on sensor

About temperature/humidity: If i disconnect the serial jumpers for a while, it starts to transmit at least one (last measured/random?) value:
homie/sens1/temperature/value 10
homie/sens1/humidity/value 13
homie/sens1/light/value 570
homie/sens1/temperature/value 10
homie/sens1/humidity/value 13
homie/sens1/light/value 595
homie/sens1/temperature/value 10
homie/sens1/humidity/value 13

So there seems to be an issue with the internal serial communication.
Actually I had same issue with the original firmware, but I had no time to debug it.

HTH
Alex

**Comment by derlucas** [comment]
Hey Alex,
the values are correctly read over the Serial connection, i debugged that. I just transfer over MQTT what comes from the atmel IC. I will look into that if and how i need to convert the values.
The problem with the missing values is currently in homie itself. There is [this Bug](https://github.com/marvinroger/homie-esp8266/issues/263) where not more than three Nodes are possible. I'm waiting for @marvinroger to look at that issue since i'm not that deep into the homie codebase.
Lucas

**Comment by derlucas** [comment]
I added the missing values by misusing one HomieNode for all values. Still need to calculate meaningful representational values for the numbers.
